export const countries = [
  { label: 'United States', value: 'US' },
  { label: 'United Kingdom', value: 'GB' },
  { label: 'India', value: 'IN' },
  { label: 'Canada', value: 'CA' },
  { label: 'Australia', value: 'AU' },
  { label: 'Germany', value: 'DE' },
  { label: 'France', value: 'FR' },
  { label: 'Italy', value: 'IT' },
  { label: 'Spain', value: 'ES' },
  { label: 'Mexico', value: 'MX' },
  { label: 'Brazil', value: 'BR' },
  { label: 'Argentina', value: 'AR' },
  { label: 'South Africa', value: 'ZA' },
  { label: 'Japan', value: 'JP' },
  { label: 'China', value: 'CN' },
  { label: 'Russia', value: 'RU' },
  { label: 'South Korea', value: 'KR' },
  { label: 'Saudi Arabia', value: 'SA' },
  { label: 'United Arab Emirates', value: 'AE' },
  { label: 'Singapore', value: 'SG' },
  { label: 'New Zealand', value: 'NZ' },
  { label: 'Netherlands', value: 'NL' },
  { label: 'Belgium', value: 'BE' },
  { label: 'Sweden', value: 'SE' },
  { label: 'Norway', value: 'NO' },
  { label: 'Denmark', value: 'DK' },
  { label: 'Finland', value: 'FI' },
  { label: 'Switzerland', value: 'CH' },
  { label: 'Norway', value: 'NO' },
  { label: 'Sweden', value: 'SE' },
  { label: 'Poland', value: 'PL' },
  { label: 'Turkey', value: 'TR' },
  { label: 'Egypt', value: 'EG' },
  { label: 'Nigeria', value: 'NG' },
  { label: 'Kenya', value: 'KE' },
  { label: 'Chile', value: 'CL' },
  { label: 'Peru', value: 'PE' },
  { label: 'Colombia', value: 'CO' },
  { label: 'Venezuela', value: 'VE' },
  { label: 'Thailand', value: 'TH' },
  { label: 'Vietnam', value: 'VN' },
  { label: 'Malaysia', value: 'MY' },
  { label: 'Indonesia', value: 'ID' },
  { label: 'Philippines', value: 'PH' },
  { label: 'Pakistan', value: 'PK' },
  { label: 'Bangladesh', value: 'BD' },
  { label: 'Nepal', value: 'NP' },
  { label: 'Sri Lanka', value: 'LK' },
  { label: 'Iraq', value: 'IQ' },
  { label: 'Jordan', value: 'JO' },
  { label: 'Israel', value: 'IL' },
  { label: 'Lebanon', value: 'LB' },
  { label: 'Kuwait', value: 'KW' },
  { label: 'Qatar', value: 'QA' },
  { label: 'Bahrain', value: 'BH' },
  { label: 'Oman', value: 'OM' },
  { label: 'Czech Republic', value: 'CZ' },
  { label: 'Slovakia', value: 'SK' },
  { label: 'Romania', value: 'RO' },
  { label: 'Ukraine', value: 'UA' },
  { label: 'Portugal', value: 'PT' },
  { label: 'Greece', value: 'GR' },
  { label: 'Hungary', value: 'HU' },
  { label: 'Croatia', value: 'HR' },
  { label: 'Serbia', value: 'RS' },
  { label: 'Bulgaria', value: 'BG' },
  { label: 'Moldova', value: 'MD' },
  { label: 'Kazakhstan', value: 'KZ' },
  { label: 'Uzbekistan', value: 'UZ' },
  { label: 'Azerbaijan', value: 'AZ' },
  { label: 'Armenia', value: 'AM' },
  { label: 'Georgia', value: 'GE' },
];
